package com.vivopulse.feature.processing.labmode

import android.content.Context
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

/**
 * Generates vascular reactivity reports for lab mode protocols.
 */
class ReactivityReportGenerator(private val context: Context) {
    
    /**
     * Generate reactivity report markdown.
     * 
     * @param analysis Reactivity analysis result
     * @param sessionId Session ID
     * @return Report file path
     */
    fun generateReport(
        analysis: ReactivityAnalysis,
        sessionId: String
    ): String {
        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
        val reportDir = File(context.getExternalFilesDir(null), "lab_mode/reports")
        reportDir.mkdirs()
        
        val reportFile = File(reportDir, "reactivity_${analysis.protocolId}_${timestamp}.md")
        
        val report = buildReport(analysis, sessionId, timestamp)
        reportFile.writeText(report)
        
        return reportFile.absolutePath
    }
    
    /**
     * Build report content.
     */
    private fun buildReport(
        analysis: ReactivityAnalysis,
        sessionId: String,
        timestamp: String
    ): String {
        return buildString {
            appendLine("# Vascular Reactivity Report")
            appendLine()
            appendLine("**Protocol:** ${analysis.protocolName}")
            appendLine("**Session ID:** $sessionId")
            appendLine("**Date:** $timestamp")
            appendLine()
            appendLine("---")
            appendLine()
            
            // Overall Reactivity Level
            appendLine("## Overall Reactivity")
            appendLine()
            appendLine("**Level:** ${formatReactivityBadge(analysis.reactivityLevel)}")
            appendLine()
            appendLine(getReactivityInterpretation(analysis.reactivityLevel))
            appendLine()
            appendLine("---")
            appendLine()
            
            // Phase-by-Phase Metrics
            appendLine("## Phase Metrics")
            appendLine()
            appendLine("| Phase | PTT (ms) | PTT SD (ms) | HR (bpm) | Correlation |")
            appendLine("|-------|----------|-------------|----------|-------------|")
            
            for ((@Suppress("UNUSED_VARIABLE") phaseId, metrics) in analysis.phaseMetrics.toList().sortedBy { 
                // Sort by phase order (assuming IDs are in order or use a custom comparator)
                it.first
            }) {
                appendLine("| ${metrics.phaseName} | ${formatValue(metrics.pttMs, 1)} | ${formatValue(metrics.pttSdMs, 1)} | ${formatValue(metrics.hrBpm, 0)} | ${formatValue(metrics.correlation, 3)} |")
            }
            appendLine()
            appendLine("---")
            appendLine()
            
            // Phase Transitions & Deltas
            appendLine("## Physiological Changes")
            appendLine()
            
            for (delta in analysis.deltas) {
                appendLine("### ${delta.phase1Name} → ${delta.phase2Name}")
                appendLine()
                appendLine("| Metric | Change | Expected | Match |")
                appendLine("|--------|--------|----------|-------|")
                
                // PTT change
                val pttChangeStr = formatDelta(delta.deltaPttMs)
                val pttExpectedStr = delta.expectedPttDirection?.let { formatDirection(it) } ?: "—"
                val pttMatchStr = formatMatch(delta.pttMatchesExpected)
                appendLine("| ΔPTT | $pttChangeStr ms | $pttExpectedStr | $pttMatchStr |")
                
                // HR change
                val hrChangeStr = formatDelta(delta.deltaHrBpm)
                val hrExpectedStr = delta.expectedHrDirection?.let { formatDirection(it) } ?: "—"
                val hrMatchStr = formatMatch(delta.hrMatchesExpected)
                appendLine("| ΔHR | $hrChangeStr bpm | $hrExpectedStr | $hrMatchStr |")
                
                // Correlation change
                val corrChangeStr = formatDelta(delta.deltaCorrScore)
                appendLine("| Δcorr | $corrChangeStr | — | — |")
                appendLine()
                
                // Interpretation
                appendLine(getTransitionInterpretation(delta))
                appendLine()
            }
            
            appendLine("---")
            appendLine()
            
            // Recommendations
            appendLine("## Recommendations")
            appendLine()
            appendLine(getRecommendations(analysis))
            appendLine()
            
            // Footer
            appendLine("---")
            appendLine()
            appendLine("*Report generated by VivoPulse Lab Mode*")
            appendLine()
            appendLine("**Note:** This report is for research and wellness purposes only. ")
            appendLine("Not intended for medical diagnosis or clinical decision-making.")
        }
    }
    
    private fun formatReactivityBadge(level: ReactivityLevel): String {
        return when (level) {
            ReactivityLevel.NORMAL -> "✅ NORMAL (responsive)"
            ReactivityLevel.LOW -> "⚠️ LOW (reduced response)"
            ReactivityLevel.BLUNTED -> "❌ BLUNTED (minimal response)"
            ReactivityLevel.UNKNOWN -> "❓ UNKNOWN (insufficient data)"
        }
    }
    
    private fun getReactivityInterpretation(level: ReactivityLevel): String {
        return when (level) {
            ReactivityLevel.NORMAL -> 
                "Your vascular system showed **normal reactivity** to the protocol challenge. " +
                "Physiological changes occurred in the expected directions (≥80% match)."
            ReactivityLevel.LOW -> 
                "Your vascular reactivity was **lower than expected** (50-80% match). " +
                "Some physiological changes occurred, but responses were inconsistent or blunted."
            ReactivityLevel.BLUNTED -> 
                "Your vascular system showed **minimal reactivity** to the challenge (<50% match). " +
                "Consider retrying with better positioning or consult the troubleshooting guide."
            ReactivityLevel.UNKNOWN -> 
                "Insufficient data to assess reactivity. Please retry the protocol."
        }
    }
    
    private fun formatValue(value: Double, decimals: Int): String {
        return String.format("%.${decimals}f", value)
    }
    
    private fun formatDelta(delta: Double): String {
        return if (delta > 0) {
            "+${formatValue(delta, 1)}"
        } else {
            formatValue(delta, 1)
        }
    }
    
    private fun formatDirection(direction: Direction): String {
        return when (direction) {
            Direction.INCREASE -> "↑ Increase"
            Direction.DECREASE -> "↓ Decrease"
            Direction.STABLE -> "↔ Stable"
        }
    }
    
    private fun formatMatch(match: Boolean?): String {
        return when (match) {
            true -> "✅ Yes"
            false -> "❌ No"
            null -> "—"
        }
    }
    
    private fun getTransitionInterpretation(delta: PhaseDelta): String {
        val pttMatch = delta.pttMatchesExpected ?: false
        val hrMatch = delta.hrMatchesExpected ?: false
        
        return if (pttMatch && hrMatch) {
            "**Interpretation:** Expected physiological response observed. Both PTT and HR changed as anticipated."
        } else if (pttMatch || hrMatch) {
            "**Interpretation:** Partial response observed. One metric changed as expected, the other did not."
        } else {
            "**Interpretation:** Unexpected response. Changes did not match expected patterns. Consider signal quality or positioning."
        }
    }
    
    private fun getRecommendations(analysis: ReactivityAnalysis): String {
        return when (analysis.reactivityLevel) {
            ReactivityLevel.NORMAL -> 
                "- Your vascular reactivity appears normal.\n" +
                "- Repeat the protocol periodically to track trends over time.\n" +
                "- Compare results across different times of day or stress levels."
            ReactivityLevel.LOW -> 
                "- Consider repeating the protocol with improved conditions:\n" +
                "  - Better lighting for face camera\n" +
                "  - More stable positioning\n" +
                "  - Less ambient noise/distraction\n" +
                "- If results remain low, this may indicate reduced autonomic flexibility."
            ReactivityLevel.BLUNTED -> 
                "- Check signal quality (SQI should be ≥70)\n" +
                "- Ensure proper finger pressure (light, not too hard)\n" +
                "- Verify face ROI stayed on forehead throughout\n" +
                "- Consider retrying at a different time of day"
            ReactivityLevel.UNKNOWN -> 
                "- Insufficient data to generate recommendations.\n" +
                "- Please retry the protocol."
        }
    }
}

